name: Trigger other project

on:
  workflow_dispatch: # Allows for manual workflow trigger

jobs:
  trigger-project-b:
    uses: dmilek/sequence_forecaster/.github/workflows/reusable.yml@main
    secrets: inherit
