# .github/workflows/trigger_project_b.yml in Project A

name: Trigger Project B Workflow

on:
  workflow_dispatch: # manual trigger

jobs:
  trigger-project-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Project B workflow via GitHub API
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # PAT with repo and workflow permissions
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/dmilek/sequence_forecaster/actions/workflows/CI_test_workflow_call.yml/dispatches \
            -d '{"ref":"main"}'
