name: Daily Scraper Workflow

on:
  workflow_dispatch: # Allows for manual workflow trigger
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 02:00 UTC

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Build and run the scraper
      - name: Run DailyScraper
        run: |
          mvn clean compile
          mvn exec:java -Dexec.mainClass="general_utils.DailyScraper"

      # Step 4: Set Git user for commit
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 5: Commit and push CSV file back to repository
      - name: Commit and push changes
        run: |
          git add scraped_numbers.csv
          git commit -m "Update scraped numbers on $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
