name: Weekly Number Analysis

on:
  schedule:
    - cron: '0 3 * * 1'  # Run every Monday at 03:00 UTC
  workflow_dispatch:  # Allows for manual workflow trigger

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'adopt'  # or 'zulu', 'adoptium', 'oracle', etc.
        java-package: jdk

    - name: Build Project
      run: mvn clean package
      
    - name: Run Analyzer
      id: run_analyzer
      run: |
        html_report=$(mvn exec:java -Dexec.mainClass="general_utils.NumberFrequencyAnalyzer" | grep "<html")
        echo "::set-output name=html_report::$html_report"

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Weekly Number Analysis'
        from: 'notification.service1988@gmail.com'  # Your sender email address
        html_body: ${{ steps.run_analyzer.outputs.html_report }}  # Use captured HTML
        to:  ${{ secrets.EMAIL_RECIPIENT }} # Replace with recipient's email
