name: Weekly Number Analysis

on:
  workflow_dispatch: # Allows for manual workflow trigger
  schedule:
    - cron: '0 3 * * 1' # Run every Monday at 03:00 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    # Step 2: Set up JDK 23
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin' 
        
    # Step 4: Build
    - name: Build Project
      run: mvn clean package
      
    # Step 5: Run the Analyzer and extract HTML report
    - name: Run NumberFrequencyAnalyzer and Capture HTML Report
      id: generate_html_report
      run: |
          html_report=$(mvn exec:java -Dexec.mainClass="general_utils.NumberFrequencyAnalyzer" | grep "<html")
          echo "html_report=$html_report" >> $GITHUB_ENV

    # Step 6: Send the report via email
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Weekly Number Analysis'
        from: 'Notification Service <notification.service1988@gmail.com>'  # Your sender email address
        html_body: ${{ env.html_report }}  # Use the captured HTML report
        to:  ${{ secrets.EMAIL_RECIPIENT }} # Replace with recipient's email
